### ISSUE TITLE
Interact key hud element

### ISSUE THREAD

**Issue by justinorringer** [adventureboss/adminquest#101]

**Comment by SteveHNH** [comment]
If you talk to Doug, he has a dialogue option where he tells you the controls. It's not obvious though. 

PR #142 fixes this *sort of*. It's not perfect but it gives you a dialogue if you press ESC

**Comment by justinorringer** [comment]
I liked the dialog option, but I had more in my mind something like this #146 . Comes and goes as you enter the npc Area2D.

![image](https://user-images.githubusercontent.com/87503474/170879755-19bc6df2-9f91-4616-b3be-ca7f173a5aec.png)
