### ISSUE TITLE
Enemy attacks from bellow the player

### ISSUE THREAD

**Issue by justinorringer** [adventureboss/adminquest#59]
I'm not sure why the enemy goes for the bottom right corner, but it makes the enemy run over things haha

![image](https://user-images.githubusercontent.com/87503474/170298949-b323644a-cd34-40a1-990f-879063866b45.png)

**Comment by josejulio** [comment]
I guess this has something to do with the "global_position". Probably need to consider the collision circle of the player instead of only the global_position.
