### ISSUE TITLE
AnimationTree & AnimationPlayer vs Sprite for enemies and NPCs

### ISSUE THREAD

**Issue by justinorringer** [adventureboss/adminquest#60]
Do we want to use Animation nodes for everything? Right now we are getting errors with the enemies and wanderer NPC.

![image](https://user-images.githubusercontent.com/87503474/170301271-e336b03c-64da-44c8-bdde-e34b448396ca.png)

**Comment by josejulio** [comment]
My idea was to use them if found - or else don't animate. 
We can use `get_node_or_null` instead to silence the errors
